spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
      url: jdbc:mysql://localhost:3306/customerapi
      username: springstudent
      password: springstudent

server:
  port: 8081